export const carsData = {
  // 1. Mercedes S-Class W221 AMG
  "mercedes-s-class-w221": {
    name: "Mercedes S-Class",
    year: 2008,
    category: "Бизнес",
    color: "Белый",
    rating: 4.9,
    reviews: 45,
    power: "400+ л.с.",
    speed: "250+ км/ч",
    volume: "5.5 л",
    description:
      "Mercedes S-Class — премиальный седан бизнес-класса с характерными AMG дисками. Идеален для VIP-встреч и мероприятий.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/1-mercedes-s-class-w221-amg-white/9.jpg",
    ],
    pricing: {
      day: { price: 45000, time: "1 день" },
      week: { price: 280000, time: "1 неделя" },
      month: { price: 900000, time: "1 месяц" },
    },
    deposit: 150000,
    insurance: 25000,
  },

  // 2. Lexus LX570
  "lexus-lx570": {
    name: "Lexus LX570",
    year: 2007,
    category: "SUV",
    color: "Черный",
    rating: 5.0,
    reviews: 52,
    power: "380 л.с.",
    speed: "210 км/ч",
    volume: "5.7 л",
    description:
      "Lexus LX570 — лучший выбор для гор, пересеченной местности и семейных поездок. 7 мест, премиальный комфорт.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/2-lexus-lx570-restyle-black/9.jpg",
    ],
    pricing: {
      day: { price: 60000, time: "1 день" },
      week: { price: 350000, time: "1 неделя" },
      month: { price: 1200000, time: "1 месяц" },
    },
    deposit: 180000,
    insurance: 30000,
  },

  // 3. Mercedes E-Class W212 AMG (2014, Белый)
  "mercedes-e-class-w212-amg-white-2014": {
    name: "Mercedes E-Class AMG",
    year: 2014,
    category: "Бизнес",
    color: "Белый",
    rating: 4.8,
    reviews: 38,
    power: "380 л.с.",
    speed: "240 км/ч",
    volume: "3.5 л",
    description:
      "Mercedes E-Class AMG — элегантный бизнес-седан с динамичным дизайном AMG. Современный комфорт для деловых поездок.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/3-mercedes-e-class-w212-amg-white/9.jpg",
    ],
    pricing: {
      day: { price: 40000, time: "1 день" },
      week: { price: 245000, time: "1 неделя" },
      month: { price: 980000, time: "1 месяц" },
    },
    deposit: 120000,
    insurance: 20000,
  },

  // 4. Hyundai Accent (Белый, 2018)
  "hyundai-accent-white": {
    name: "Hyundai Accent",
    year: 2018,
    category: "Эконом",
    color: "Белый",
    rating: 4.6,
    reviews: 28,
    power: "120 л.с.",
    speed: "180 км/ч",
    volume: "1.6 л",
    description: "Hyundai Accent — надежный и экономичный автомобиль эконом-класса. Идеален для городских поездок.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/4-hyundai-accent-white-2018/9.jpg",
    ],
    pricing: {
      day: { price: 15000, time: "1 день" },
      week: { price: 98000, time: "1 неделя" },
      month: { price: 380000, time: "1 месяц" },
    },
    deposit: 40000,
    insurance: 8000,
  },

  // 5. Hyundai Accent (Красный, 2012)
  "hyundai-accent-red": {
    name: "Hyundai Accent",
    year: 2012,
    category: "Эконом",
    color: "Красный",
    rating: 4.5,
    reviews: 22,
    power: "120 л.с.",
    speed: "180 км/ч",
    volume: "1.6 л",
    description: "Hyundai Accent — экономичный автомобиль эконом-класса для бюджетного путешествия.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/5-hyundai-accent-red-2012/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/5-hyundai-accent-red-2012/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/5-hyundai-accent-red-2012/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/5-hyundai-accent-red-2012/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/5-hyundai-accent-red-2012/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/5-hyundai-accent-red-2012/6.jpg",
    ],
    pricing: {
      day: { price: 14000, time: "1 день" },
      week: { price: 98000, time: "1 неделя" },
      month: { price: 392000, time: "1 месяц" },
    },
    deposit: 38000,
    insurance: 7500,
  },

  // 6. Hyundai Accent (Черный, 2018)
  "hyundai-accent-black": {
    name: "Hyundai Accent",
    year: 2018,
    category: "Эконом",
    color: "Черный",
    rating: 4.6,
    reviews: 29,
    power: "120 л.с.",
    speed: "180 км/ч",
    volume: "1.6 л",
    description: "Hyundai Accent — надежный и экономичный автомобиль эконом-класса. Идеален для городских поездок.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/6-hyundai-accent-black-2018/9.jpg",
    ],
    pricing: {
      day: { price: 15000, time: "1 день" },
      week: { price: 98000, time: "1 неделя" },
      month: { price: 380000, time: "1 месяц" },
    },
    deposit: 40000,
    insurance: 8000,
  },

  // 7. Bentley Continental GT
  "bentley-continental-gt": {
    name: "Bentley Continental GT",
    year: 2007,
    category: "Люкс",
    color: "Белый",
    rating: 5.0,
    reviews: 18,
    power: "600 л.с.",
    speed: "300+ км/ч",
    volume: "6.0 л",
    description:
      "Bentley Continental GT — вершина люкса и производительности. Уникальный статус-символ с индивидуальным обвесом.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/9.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/10.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/11.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/12.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/13.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/14.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/15.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/7-bentley-continental-gt-white/16.jpg",
    ],
    pricing: {
      day: { price: 100000, time: "1 день" },
      week: { price: 650000, time: "1 неделя" },
      month: { price: 2300000, time: "1 месяц" },
    },
    deposit: 300000,
    insurance: 50000,
  },

  // 8. Lexus IS (Красный)
  "lexus-is-red": {
    name: "Lexus IS",
    year: 2013,
    category: "Спорт",
    color: "Красный",
    rating: 4.8,
    reviews: 35,
    power: "350 л.с.",
    speed: "230 км/ч",
    volume: "3.5 л",
    description: "Lexus IS — спортивный премиум-седан с динамичным характером. Идеален для активных водителей.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/8-lexus-is-red/9.jpg",
    ],
    pricing: {
      day: { price: 30000, time: "1 день" },
      week: { price: 170000, time: "1 неделя" },
      month: { price: 550000, time: "1 месяц" },
    },
    deposit: 90000,
    insurance: 15000,
  },

  // 9. Mercedes E-Class W212 (Черный, 2010)
  "mercedes-e-class-w212-black-2010": {
    name: "Mercedes E-Class",
    year: 2010,
    category: "Бизнес",
    color: "Черный",
    rating: 4.7,
    reviews: 32,
    power: "280 л.с.",
    speed: "230 км/ч",
    volume: "3.0 л",
    description:
      "Mercedes E-Class — классический бизнес-седан с высоким уровнем комфорта. Отличный выбор для деловых встреч.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/9-mercedes-e-class-w212-black/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/9-mercedes-e-class-w212-black/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/9-mercedes-e-class-w212-black/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/9-mercedes-e-class-w212-black/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/9-mercedes-e-class-w212-black/5.jpg",
    ],
    pricing: {
      day: { price: 24000, time: "1 день" },
      week: { price: 138000, time: "1 неделя" },
      month: { price: 500000, time: "1 месяц" },
    },
    deposit: 75000,
    insurance: 12000,
  },

  // 10. Mercedes E-Class W212 AMG (Черный, 2014)
  "mercedes-e-class-w212-amg-black": {
    name: "Mercedes E-Class AMG",
    year: 2014,
    category: "Бизнес",
    color: "Черный",
    rating: 4.9,
    reviews: 41,
    power: "380 л.с.",
    speed: "240 км/ч",
    volume: "3.5 л",
    description: "Mercedes E-Class AMG — мощный и элегантный бизнес-седан с агрессивным дизайном AMG Line.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/10-mercedes-e-class-w212-amg-black/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/10-mercedes-e-class-w212-amg-black/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/10-mercedes-e-class-w212-amg-black/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/10-mercedes-e-class-w212-amg-black/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/10-mercedes-e-class-w212-amg-black/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/10-mercedes-e-class-w212-amg-black/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/10-mercedes-e-class-w212-amg-black/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/10-mercedes-e-class-w212-amg-black/8.jpg",
    ],
    pricing: {
      day: { price: 45000, time: "1 день" },
      week: { price: 250000, time: "1 неделя" },
      month: { price: 900000, time: "1 месяц" },
    },
    deposit: 135000,
    insurance: 22000,
  },

  // 11. Infiniti QX80
  "infiniti-qx80": {
    name: "Infiniti QX80",
    year: 2017,
    category: "SUV",
    color: "Черный",
    rating: 4.9,
    reviews: 48,
    power: "400 л.с.",
    speed: "220 км/ч",
    volume: "5.6 л",
    description:
      "Infiniti QX80 — премиальный внедорожник на 7 мест с круиз-контролем, камерами. Мощный мотор. Подходит для трасс и города.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/9.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/10.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/11.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/12.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/13.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/14.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/15.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/11-infiniti-qx80-black/16.jpg",
    ],
    pricing: {
      day: { price: 80000, time: "1 день" },
      week: { price: 490000, time: "1 неделя" },
      month: { price: 1700000, time: "1 месяц" },
    },
    deposit: 200000,
    insurance: 35000,
  },

  // 12. Cadillac Escalade ESV
  "cadillac-escalade-esv": {
    name: "Cadillac Escalade ESV",
    year: 2007,
    category: "SUV",
    color: "Черный",
    rating: 4.7,
    reviews: 39,
    power: "400 л.с.",
    speed: "200 км/ч",
    volume: "6.2 л",
    description: "Cadillac Escalade ESV — удлиненная версия с 7–8 местами и большим комфортом. Огромный багажник.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/12-cadillac-escalade-esv-black/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/12-cadillac-escalade-esv-black/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/12-cadillac-escalade-esv-black/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/12-cadillac-escalade-esv-black/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/12-cadillac-escalade-esv-black/5.jpg",
    ],
    pricing: {
      day: { price: 47500, time: "1 день" },
      week: { price: 290000, time: "1 неделя" },
      month: { price: 850000, time: "1 месяц" },
    },
    deposit: 140000,
    insurance: 23000,
  },

  // 13. Kia Rio
  "kia-rio": {
    name: "Kia Rio",
    year: 2020,
    category: "Эконом",
    color: "Черный",
    rating: 4.6,
    reviews: 31,
    power: "120 л.с.",
    speed: "180 км/ч",
    volume: "1.6 л",
    description: "Kia Rio — современный и экономичный автомобиль. Удобен для городских поездок и путешествий.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/9.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/13-kia-rio-black/10.jpg",
    ],
    pricing: {
      day: { price: 15000, time: "1 день" },
      week: { price: 98000, time: "1 неделя" },
      month: { price: 380000, time: "1 месяц" },
    },
    deposit: 40000,
    insurance: 8000,
  },

  // 14. Toyota Land Cruiser 200
  "toyota-land-cruiser-200": {
    name: "Toyota Land Cruiser 200",
    year: 2008,
    category: "SUV",
    color: "Черный",
    rating: 4.8,
    reviews: 52,
    power: "280 л.с.",
    speed: "200 км/ч",
    volume: "4.7 л",
    description:
      "Toyota Land Cruiser 200 — легендарный премиальный внедорожник с отличной проходимостью. Идеален для любых дорог.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/9.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/14-toyota-land-cruiser-200-black/10.jpg",
    ],
    pricing: {
      day: { price: 55000, time: "1 день" },
      week: { price: 350000, time: "1 неделя" },
      month: { price: 850000, time: "1 месяц" },
    },
    deposit: 165000,
    insurance: 27000,
  },

  // 15. Mercedes E-Class W212 AMG (Белый)
  "mercedes-e-class-w212-amg-white": {
    name: "Mercedes E-Class AMG",
    year: 2015,
    category: "Бизнес",
    color: "Белый",
    rating: 4.8,
    reviews: 40,
    power: "380 л.с.",
    speed: "240 км/ч",
    volume: "3.5 л",
    description:
      "Mercedes E-Class AMG — элегантный бизнес-седан с динамичным дизайном AMG. Премиальный комфорт и производительность.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/15-mercedes-e-class-w212-amg-white/9.jpg",
    ],
    pricing: {
      day: { price: 35000, time: "1 день" },
      week: { price: 200000, time: "1 неделя" },
      month: { price: 700000, time: "1 месяц" },
    },
    deposit: 105000,
    insurance: 18000,
  },

  // 16. Porsche Cayenne (Черный)
  "porsche-cayenne-black": {
    name: "Porsche Cayenne",
    year: 2008,
    category: "SUV",
    color: "Черный",
    rating: 4.8,
    reviews: 36,
    power: "320 л.с.",
    speed: "230 км/ч",
    volume: "4.8 л",
    description:
      "Porsche Cayenne — премиальный спортивный внедорожник с мощным двигателем. Для ценителей производительности.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/16-porsche-cayenne-black/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/16-porsche-cayenne-black/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/16-porsche-cayenne-black/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/16-porsche-cayenne-black/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/16-porsche-cayenne-black/5.jpg",
    ],
    pricing: {
      day: { price: 40000, time: "1 день" },
      week: { price: 250000, time: "1 неделя" },
      month: { price: 700000, time: "1 месяц" },
    },
    deposit: 120000,
    insurance: 20000,
  },

  // 17. Porsche Cayenne (Серебристый)
  "porsche-cayenne-silver": {
    name: "Porsche Cayenne",
    year: 2011,
    category: "SUV",
    color: "Серебристый",
    rating: 4.8,
    reviews: 38,
    power: "340 л.с.",
    speed: "235 км/ч",
    volume: "4.8 л",
    description:
      "Porsche Cayenne — премиальный внедорожник с современным дизайном и мощным двигателем. Комфорт и спорт.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/9.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/10.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/11.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/12.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/13.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/14.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/17-porsche-cayenne-silver/15.jpg",
    ],
    pricing: {
      day: { price: 45000, time: "1 день" },
      week: { price: 280000, time: "1 неделя" },
      month: { price: 750000, time: "1 месяц" },
    },
    deposit: 135000,
    insurance: 22000,
  },

  // 18. Range Rover Vogue
  "range-rover-vogue": {
    name: "Range Rover Vogue",
    year: 2015,
    category: "Люкс",
    color: "Белый",
    rating: 5.0,
    reviews: 44,
    power: "380 л.с.",
    speed: "240 км/ч",
    volume: "4.4 л",
    description:
      "Range Rover Vogue — вершина люкса и комфорта. Роскошный интерьер и передовые технологии для любого типа местности.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/8.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/9.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/10.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/11.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/12.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/13.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/18-range-rover-vogue-white/14.jpg",
    ],
    pricing: {
      day: { price: 90000, time: "1 день" },
      week: { price: 500000, time: "1 неделя" },
      month: { price: 1400000, time: "1 месяц" },
    },
    deposit: 250000,
    insurance: 40000,
  },

  // 19. Mercedes CL-Class C216
  "mercedes-cl-class-c216": {
    name: "Mercedes CL-Class",
    year: 2009,
    category: "Премиум",
    color: "Серый",
    rating: 4.9,
    reviews: 28,
    power: "500 л.с.",
    speed: "250 км/ч",
    volume: "5.5 л",
    description:
      "Mercedes CL-Class — потрясающее премиум-купе с роскошным интерьером и мощным двигателем. Стиль и производительность.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/cars/19-mercedes-cl-class-c216-grey/1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/19-mercedes-cl-class-c216-grey/2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/19-mercedes-cl-class-c216-grey/3.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/19-mercedes-cl-class-c216-grey/4.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/19-mercedes-cl-class-c216-grey/5.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/19-mercedes-cl-class-c216-grey/6.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/19-mercedes-cl-class-c216-grey/7.jpg",
      "https://alchinkaz.github.io/db-dream-rent/cars/19-mercedes-cl-class-c216-grey/8.jpg",
    ],
    pricing: {
      day: { price: 62500, time: "1 день" },
      week: { price: 350000, time: "1 неделя" },
      month: { price: 1000000, time: "1 месяц" },
    },
    deposit: 200000,
    insurance: 35000,
  },
}
