export const motorcycleData = {
  "samurai": {
    name: "SAMURAI",
    year: 2024,
    category: "Мопед",
    rating: 4.9,
    reviews: 45,
    power: "9.0 л.с.",
    speed: "90 км/ч",
    volume: "150 см³",
    description: "Современный SAMURAI оснащён мощным 150 см³ двигателем, выдающим 9.0 л.с. — лёгкий, резкий и надёжный. Развивает скорость до 90 км/ч, идеально подходит как для города, так и для трассы. Благодаря автоматической коробке передач (вариатору) — управлять просто и удобно, даже для новичков. Самурай отличается улучшенной подвеской и устойчивостью — езда мягкая, управляемость отличная даже на неровных дорогах.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/scoots/samurai/samurai-1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/samurai/samurai-2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/samurai/samurai-3.jpg",
    ],
    pricing: {
      day: { price: 6000, time: "1 день" },
      twoDays: { price: 12000, time: "2 дня" },
      week: { price: 27000, time: "1 неделя" },
    },
    helmet: "бесплатно",
    insurance: 6000,
  },
  "m8": {
    name: "M8",
    year: 2024,
    category: "Мопед",
    rating: 4.8,
    reviews: 38,
    power: "9.5 л.с.",
    speed: "95 км/ч",
    volume: "150 см³",
    description: "Современный M8 — это сочетание стиля, мощности и комфорта. Двигатель 157QMJ, 150 см³, мощностью 9.5 л.с., развивает скорость до 95 км/ч. Автоматическая трансмиссия (вариатор) обеспечивает плавность хода и лёгкость управления. Благодаря усиленной раме и обновлённой подвеске, M8 уверенно чувствует себя и на городских улицах, и на подъёмах.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/scoots/m8/m8-1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/m8/m8-2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/m8/m8-3.jpg",
    ],
    pricing: {
      day: { price: 5500, time: "1 день" },
      twoDays: { price: 11000, time: "2 дня" },
      week: { price: 25000, time: "1 неделя" },
    },
    helmet: "бесплатно",
    insurance: 6000,
  },
  "maxi": {
    name: "MAXI",
    year: 2024,
    category: "Мопед",
    rating: 4.7,
    reviews: 52,
    power: "9.2 л.с.",
    speed: "85 км/ч",
    volume: "150 см³",
    description: "MAXI — это надёжный и практичный мопед с двигателем 150 см³ и мощностью 9.2 л.с. Развивает скорость до 85 км/ч, что делает его отличным выбором для городских поездок. Вариатор обеспечивает комфортное управление, а просторное сиденье гарантирует удобство даже в длительных поездках.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/scoots/maxi/maxi-1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/maxi/maxi-2.jpg",
    ],
    pricing: {
      day: { price: 6500, time: "1 день" },
      twoDays: { price: 13000, time: "2 дня" },
      week: { price: 35000, time: "1 неделя" },
    },
    helmet: "бесплатно",
    insurance: 6000,
  },
  "maxi-sport": {
    name: "MAXI SPORT",
    year: 2024,
    category: "Мопед",
    rating: 5.0,
    reviews: 31,
    power: "10.5 л.с.",
    speed: "100 км/ч",
    volume: "150 см³",
    description: "MAXI SPORT — это топовая версия с улучшенными характеристиками. Двигатель 150 см³ выдаёт 10.5 л.с. и развивает скорость до 100 км/ч. Спортивная подвеска и улучшенная аэродинамика делают этот мопед идеальным для тех, кто ценит динамику и стиль. Оснащён всеми современными системами безопасности.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/scoots/maxi/maxi-sport-1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/maxi/maxi-sport-2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/maxi/maxi-sport-3.jpg",
    ],
    pricing: {
      day: { price: 7500, time: "1 день" },
      twoDays: { price: 15000, time: "2 дня" },
      week: { price: 35000, time: "1 неделя" },
    },
    helmet: "бесплатно",
    insurance: 6000,
  },
  "yamaha-r1-2015": {
    name: "YAMAHA R1",
    year: 2015,
    category: "Спортбайк",
    rating: 4.8,
    reviews: 157,
    power: "200 л.с.",
    speed: "300 км/ч",
    volume: "1000 см",
    description: "Легендарный спортбайк Yamaha R1 2015 года представляет собой идеальное сочетание мощности, управляемости и современных технологий. Этот мотоцикл создан для тех, кто ищет настоящие эмоции от вождения и готов испытать адреналин на каждом километре пути.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 25000, time: "1 день" },
      week: { price: 150000, time: "1 неделя" },
    },
    deposit: 50000,
    helmet: "бесплатно",
  },
  "bmw-s1000rr-2021": {
    name: "BMW S 1000RR",
    year: 2021,
    category: "Спортбайк",
    rating: 4.9,
    reviews: 203,
    power: "207 л.с.",
    speed: "299 км/ч",
    volume: "1000 см",
    description: "BMW S 1000RR 2021 года - это вершина немецкой инженерии в мире спортбайков. Оснащенный передовыми системами безопасности и мощным двигателем, этот мотоцикл предлагает непревзойденный опыт управления как на треке, так и на городских дорогах.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 24000, time: "1 день" },
      week: { price: 144000, time: "1 неделя" },
    },
    deposit: 50000,
    helmet: "бесплатно",
  },
  "kawasaki-ninja-650-2021": {
    name: "KAWASAKI NINJA 650",
    year: 2021,
    category: "Спортбайк",
    rating: 4.7,
    reviews: 89,
    power: "68 л.с.",
    speed: "200 км/ч",
    volume: "650 см",
    description: "Kawasaki Ninja 650 - это идеальный выбор для тех, кто хочет почувствовать динамику спортбайка с комфортом повседневной езды. Сбалансированная мощность и отличная управляемость делают этот мотоцикл универсальным спутником для любых дорог.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 12000, time: "1 день" },
      week: { price: 72000, time: "1 неделя" },
    },
    deposit: 30000,
    helmet: "бесплатно",
  },
  "suzuki-gsx-r750-2018": {
    name: "SUZUKI GSX-R750",
    year: 2018,
    category: "Спортбайк",
    rating: 4.6,
    reviews: 124,
    power: "148 л.с.",
    speed: "280 км/ч",
    volume: "750 см",
    description: "Suzuki GSX-R750 - классический спортбайк среднего объема, который сочетает в себе мощность литрового байка с маневренностью 600-кубового. Это отличный выбор для опытных райдеров, ищущих золотую середину между производительностью и управляемостью.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 13000, time: "1 день" },
      week: { price: 78000, time: "1 неделя" },
    },
    deposit: 35000,
    helmet: "бесплатно",
  },
  "bmw-s1000rr-2013": {
    name: "BMW S1000RR",
    year: 2013,
    category: "Спортбайк",
    rating: 4.5,
    reviews: 178,
    power: "193 л.с.",
    speed: "299 км/ч",
    volume: "1000 см",
    description: "BMW S1000RR 2013 года - это проверенная временем легенда на двух колесах. Несмотря на год выпуска, этот мотоцикл продолжает впечатлять своей мощностью, надежностью и спортивным характером, оставаясь одним из лучших выборов для любителей скорости.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 20000, time: "1 день" },
      week: { price: 120000, time: "1 неделя" },
    },
    deposit: 45000,
    helmet: "бесплатно",
  },
  "bmw-s1000rr-2020": {
    name: "BMW S1000RR",
    year: 2020,
    category: "Спортбайк",
    rating: 4.9,
    reviews: 156,
    power: "207 л.с.",
    speed: "299 км/ч",
    volume: "1000 см",
    description: "BMW S1000RR 2020 года представляет новейшее поколение баварских спортбайков с обновленным дизайном и усовершенствованной электроникой. Этот мотоцикл предлагает максимальную производительность и безопасность, делая каждую поездку незабываемой.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 30000, time: "1 день" },
      week: { price: 180000, time: "1 неделя" },
    },
    deposit: 50000,
    helmet: "бесплатно",
  },
  "honda-cbr-600rr-2012": {
    name: "HONDA CBR 600RR",
    year: 2012,
    category: "Спортбайк",
    rating: 4.4,
    reviews: 92,
    power: "120 л.с.",
    speed: "260 км/ч",
    volume: "600 см",
    description: "Honda CBR 600RR - это икона класса 600cc, известная своей надежностью и выдающейся управляемостью. Отличный выбор как для начинающих спортивных райдеров, так и для опытных мотоциклистов, ценящих проверенное японское качество.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 11000, time: "1 день" },
      week: { price: 66000, time: "1 неделя" },
    },
    deposit: 25000,
    helmet: "бесплатно",
  },
  "yamaha-r1-2009": {
    name: "YAMAHA R1",
    year: 2009,
    category: "Спортбайк",
    rating: 4.3,
    reviews: 134,
    power: "182 л.с.",
    speed: "295 км/ч",
    volume: "1000 см",
    description: "Yamaha R1 2009 года - это классика мотоспорта, сохранившая свой неповторимый характер и агрессивный стиль. Этот мотоцикл подарит вам незабываемые эмоции и позволит почувствовать истинный дух спортивного байка легендарной серии R1.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 20000, time: "1 день" },
      week: { price: 120000, time: "1 неделя" },
    },
    deposit: 40000,
    helmet: "бесплатно",
  },
  "kawasaki-ninja-650-2018": {
    name: "KAWASAKI NINJA 650",
    year: 2018,
    category: "Спортбайк",
    rating: 4.5,
    reviews: 76,
    power: "68 л.с.",
    speed: "200 км/ч",
    volume: "650 см",
    description: "Kawasaki Ninja 650 2018 года - это современный универсальный спортбайк, который прекрасно подходит для ежедневных поездок и выходных поездок за город. Комфортная посадка и уверенная динамика делают его отличным выбором для райдеров разного уровня.",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    pricing: {
      day: { price: 11000, time: "1 день" },
      week: { price: 66000, time: "1 неделя" },
    },
    deposit: 25000,
    helmet: "бесплатно",
  },
  "honda-dio": {
    name: "Honda Dio",
    year: 2024,
    category: "Мопед",
    rating: 4.9,
    reviews: 42,
    power: "Надёжный 50 см³",
    speed: "55 км/ч",
    volume: "50 см³",
    description: "Honda Dio оснащён надёжным 50 см³ двигателем — экономичный, уверенный и идеально подходит для ежедневных поездок. Развивает скорость до 55 км/ч, легко держится в городском потоке. Благодаря автоматической коробке (вариатору) управление максимально простое — идеально для новичков. Dio отличается комфортной подвеской, высокой манёвренностью и стабильностью — едите мягко, плавно и уверенно в любых условиях.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/scoots/honda-dio/hondadio1.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/honda-dio/hondadio2.jpg",
      "https://alchinkaz.github.io/db-dream-rent/scoots/honda-dio/hondadio3.jpg",
    ],
    pricing: {
      day: { price: 5000, time: "1 день" },
      twoDays: { price: 10000, time: "2 дня" },
      week: { price: 25000, time: "1 неделя" },
    },
    helmet: "бесплатно",
    insurance: 6000,
  },
  "peda-hornet": {
    name: "Peda Hornet",
    year: 2024,
    category: "Мопед",
    rating: 4.95,
    reviews: 38,
    power: "4-тактный 150–180 см³",
    speed: "105 км/ч",
    volume: "150–180 см³",
    description: "Peda Hornet оснащён надёжным 150–180 см³ 4-тактным двигателем — динамичный, уверенный и отлично подходит для активной езды. Развивает скорость до 90–105 км/ч, легко держит городской поток и уверенно чувствует себя на трассе. Автоматическая трансмиссия (вариатор) делает управление простым и удобным даже для новичков. Hornet отличается спортивным дизайном, прочным пластиковым обвесом и улучшенной подвеской — езда плавная, устойчивость высокая, комфорт сохраняется даже на неровной дороге.",
    images: [
      "https://alchinkaz.github.io/db-dream-rent/scoots/peda-hornet/peda-hornet-1.jpg",
    ],
    pricing: {
      day: { price: 6500, time: "1 день" },
      week: { price: 30000, time: "1 неделя" },
    },
    helmet: "бесплатно",
    insurance: 6000,
  },
}
